contentstack/live-preview-sdk

package.json, src/__test__/contentstack-live-preview-HOC.test.ts, src/contentstack-live-preview-HOC.ts, src/live-preview.ts, src/utils/onCookieChange.ts, tsconfig.json
=> feat: cookie support for SSR fetch request

docs/live-preview-configs.md, package-lock.json, package.json, src/live-preview.ts, src/utils/index.ts
1. Add live preview hash, content type uid and entry uid query params in all the “a” tag available on user’s preview page
2. Updated readme file for onLiveEdit function
=> feat: added support for live preview ssr 2.0

src/__test__/live-preview.test.ts, src/live-preview.ts, src/utils/__test__/index.test.ts, src/utils/defaults.ts, src/utils/handleUserConfig.ts, src/utils/index.ts, src/utils/types.ts
feat: added one more key to edit button to enable or disable the query param to include button
=> feat: added one more key to edit button to enable or disable the query param

src/__test__/live-preview.test.ts, src/live-preview.ts, src/liveEditor/index.ts, src/utils/__test__/handleUserConfig.test.ts, src/utils/defaults.ts, src/utils/handleUserConfig.ts, src/utils/types.ts
Please note the test cases will be added in a separate ticket.
fixes: https://contentstack.atlassian.net/browse/VC-163
=> feat: SDK redirects to client url params.

src/__test__/live-preview.test.ts, src/live-preview.ts, src/liveEditor/index.ts, src/utils/__test__/handleUserConfig.test.ts, src/utils/defaults.ts, src/utils/handleUserConfig.ts, src/utils/types.ts
The Live editor will only trigger if the mode is set to "editor" or higher.
fixes: https://contentstack.atlassian.net/browse/VC-160
=> feat: Mode support for live editor

src/__test__/live-preview.test.ts, src/live-preview.ts, src/liveEditor/index.ts, src/liveEditor/utils/generateStartEditingButton.ts, src/utils/__test__/handleUserConfig.test.ts, src/utils/defaults.ts, src/utils/handleUserConfig.ts, src/utils/types.ts
- should prioritize API key from user config
- should set API key from headers if available
- should reset API key if it is not passed
- should throw an error if the API key is not passed in editor mode
- should prioritize environment from user config
- should set environment from stack SDK if available
- should reset environment if it is not passed
- should throw an error if the environment is not passed in editor mode
- should prioritize branch from user config
- should set branch from headers if available
- should reset branch if it is not passed
fixes: https://contentstack.atlassian.net/browse/VC-161
=> feat: handle stack details for editor mode

src/liveEditor/__test__/index.test.ts, src/liveEditor/index.ts, src/liveEditor/utils/__test__/getFieldType.test.ts, src/liveEditor/utils/generateFieldSchemaMap.ts, src/liveEditor/utils/getFieldType.ts, src/liveEditor/utils/types/index.types.ts, src/types/contentTypeSchema.types.ts, src/types/cslp.types.ts, src/types/liveEditor.types.ts, src/utils/cslpdata.ts
The file is ts ignored as the typescript is not properly provide the types.
fixes: https://contentstack.atlassian.net/browse/VC-179
=> feat: add proper support for getFieldTypes

src/liveEditor/__test__/__snapshots__/index.test.ts.snap, src/liveEditor/index.ts, src/liveEditor/utils/__test__/constants.test.ts, src/liveEditor/utils/__test__/handleFieldMouseDown.test.ts, src/liveEditor/utils/constants.ts, src/liveEditor/utils/handleFieldMouseDown.ts, src/styles.css
fixes: https://contentstack.atlassian.net/browse/VC-200
=> feat: handle visual editor number fields

src/liveEditor/__test__/__snapshots__/index.test.ts.snap, src/liveEditor/__test__/index.test.ts, src/liveEditor/utils/__test__/__snapshots__/generateVisualEditorDom.test.ts.snap, src/liveEditor/utils/generateVisualEditorDom.ts
fixes: https://contentstack.atlassian.net/browse/VC-182
=> test: handle overlay DOM for inline editing

.github/workflows/update-copyright-years-in-license-file.yml
This script updates the date in the LICENSE file on the new year.
fixes: https://contentstack.atlassian.net/browse/CS-26246
=> chore: auto update copyright date in LICENSE

src/__test__/live-preview.test.ts, src/contentstack-live-preview-HOC.ts, src/live-preview.ts, src/utils/__test__/confighandler.test.ts, src/utils/configHandler.ts, src/utils/defaults.ts
Previously, the config was managed by the live preview module, making it difficult to use and update it elsewhere. The new Config handler will be a new manager that handles the parsing and retrieval of the config.
fixes: https://contentstack.atlassian.net/browse/EB-561
=> feat: add config handler

package-lock.json, package.json
and configuration
fixes: EB-676-config-support-in-adv-post-message
=> chore: update @contentstack/advanced-post-message version

package-lock.json, package.json, src/liveEditor/__test__/__snapshots__/index.test.ts.snap, src/liveEditor/__test__/index.test.ts, src/liveEditor/utils/__test__/__snapshots__/focusOverlayWrapper.test.ts.snap, src/liveEditor/utils/__test__/focusOverlayWrapper.test.ts, src/liveEditor/utils/constants.ts, src/liveEditor/utils/focusOverlayWrapper.ts
Fixes: https://contentstack.atlassian.net/browse/EB-656
=> feat: update outline styles

src/liveEditor/index.ts, src/liveEditor/utils/types/postMessage.types.ts, src/styles.css
fixes: https://contentstack.atlassian.net/browse/EB-782
=> feat: move btn to right and add focus event

src/utils/__test__/cslpdata.test.ts, src/utils/cslpdata.ts
fixes: https://contentstack.atlassian.net/browse/EB-834
=> fix: add instance returned incorrect index

.eslintrc.js, src/live-preview.ts, src/liveEditor/__test__/index.test.ts, src/liveEditor/__test__/visualEditorHover.test.ts, src/liveEditor/__test__/withoutIframe.test.ts, src/liveEditor/index.ts, src/liveEditor/utils/__test__/generateStartEditingButton.test.ts, src/liveEditor/utils/generateStartEditingButton.ts, src/types/liveEditor.types.ts, src/types/types.ts, src/utils/__test__/index.test.ts
fixes: https://contentstack.atlassian.net/browse/EB-807
=> feat: live editor url contains the target url in search param

src/__test__/live-preview.test.ts, src/live-preview.ts, src/liveEditor/index.ts, src/styles.css, src/types/types.ts, src/utils/cslpdata.ts, src/utils/defaults.ts, src/utils/inIframe.ts
The edit button should be visible outside the Visual Editor.
fixes: https://contentstack.atlassian.net/browse/EB-821
=> feat: conditionally add edit button

src/liveEditor/utils/__test__/pseudoEditableField.test.ts, src/liveEditor/utils/focusOverlayWrapper.ts, src/liveEditor/utils/handleIndividualFields.ts, src/liveEditor/utils/pseudoEditableField.ts, src/liveEditor/utils/types/postMessage.types.ts
If the field's value does not match the entry value, We create a separate edit field and update it.
fixes: https://contentstack.atlassian.net/browse/EB-818
=> feat: support test ellipsis in edit field

src/live-preview.ts, src/styles.css, src/utils/__test__/handleUserConfig.test.ts
fix: EB-(761) Live edit button doesn't go away on page navigation
=> fix: EB-(761) Live edit button doesn't go away on page navigation

README.md, main.mustache, package.json, src/__test__/live-preview.test.ts, src/live-preview.ts, src/utils/__test__/handleUserConfig.test.ts, src/utils/defaults.ts, src/utils/handleUserConfig.ts, src/utils/types.ts
Branch support for Edit button
=> Branch support for Edit button

src/liveEditor/utils/handleIndividualFields.ts
Work has been completed on this Jira story : https://contentstack.atlassian.net/browse/EB-1566
This PR focuses on fixing the highlight issue on few particular fields on the `live-preview-sdk` side.
- Literally a one line change (removed `return` from one of the functions and the flow resumed properly)
=> EB-1566: Few fields like links groups etc are not highlighted properly

src/liveEditor/components/emptyBlock.tsx, src/liveEditor/generators/generateEmptyBlock.tsx, src/liveEditor/index.ts, src/liveEditor/listeners/mouseClick.ts, src/styles.css
Ref: [EB-10](https://contentstack.atlassian.net/browse/EB-10?atlOrigin=eyJpIjoiYWZlNGFhMzQxOTgxNDI5MTk0NmIyNjZmZTRhNjI3OWYiLCJwIjoiaiJ9)
[EB-10]: https://contentstack.atlassian.net/browse/EB-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  Introduced `EmptyBlocks` for handling empty block entries 

src/liveEditor/generators/generateOverlay.tsx
Ref: [EB-1887](https://contentstack.atlassian.net/browse/EB-1887?atlOrigin=eyJpIjoiOTU2MzJjODA4YjNiNGY3YzgzZWJjZDM5NzI5ZjRkZTkiLCJwIjoiaiJ9)
[EB-1887]: https://contentstack.atlassian.net/browse/EB-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix for website shaking due to overlay

src/__test__/live-preview.test.ts, src/live-preview.ts
fix: edit button was removed from document because of nextjs router p)ush and replace method
=> fix: edit button was removed from document

package-lock.json, package.json, src/cslp/cslpdata.ts, src/liveEditor/__test__/fields/number/number.test.ts, src/liveEditor/generators/generateOverlay.tsx, src/liveEditor/index.ts, src/liveEditor/listeners/keyboardShortcuts.ts, src/liveEditor/listeners/mouseClick.ts, src/liveEditor/listeners/mouseHover.ts, src/liveEditor/utils/handleIndividualFields.ts
- Add fixed test cases under `__test__/fields`
- Escape key to un-focus focussed field
=> feat: handling number fields

package-lock.json, package.json, src/liveEditor/components/visualEditor.tsx, src/liveEditor/generators/generateDatePicker.tsx, src/liveEditor/index.ts, src/liveEditor/listeners/keyboardShortcuts.ts, src/liveEditor/listeners/mouseClick.ts, src/liveEditor/utils/convertToISO8601UTC.ts, src/liveEditor/utils/handleIndividualFields.ts, src/styles.css, tsconfig.json, webpack.common.js
- Implements [VE-25](https://contentstack.atlassian.net/browse/VE-25)
- Uses `DateTimePicker2` from Venus components to show a date picker for Date field
- Uses `floating-ui/dom` for datepicker popup positioning
[VE-25]: https://contentstack.atlassian.net/browse/VE-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: handling date fields

.github/workflows/sast-scan.yml, .husky/pre-commit, README.md, package.json, src/__test__/contentstack-live-preview-HOC.test.ts, src/__test__/live-preview.test.ts, src/live-preview.ts, src/utils/__test__/handleUserConfig.test.ts, src/utils/defaults.ts, src/utils/handleUserConfig.ts, src/utils/types.ts, tsup.config.js
=> 1.4.3 release for v2 SDK

src/liveEditor/generators/generateHoverOutline.tsx, src/liveEditor/listeners/mouseHover.ts, src/styles.css
Ref: [VE-2058](https://contentstack.atlassian.net/jira/software/c/projects/VE/boards/261?assignee=712020%3Ab2d2140a-9ef8-4af9-8fda-a4bc57ce93da&selectedIssue=VE-2058&atlOrigin=eyJpIjoiNTJkMjQxYjc1MGQ1NDU1ZTgxNzgxMzZhNzc3NjQ5NDkiLCJwIjoiaiJ9)
[VE-2058]: https://contentstack.atlassian.net/browse/VE-2058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Overlay changes to stop anchor tag navigation

src/liveEditor/generators/generateOverlay.tsx
Ref: [VE-2204](https://contentstack.atlassian.net/browse/VE-2204?atlOrigin=eyJpIjoiYWZjNzAzYWFmN2YzNDA1YzgzYWMyZGM2YmVhYmQzNGIiLCJwIjoiaiJ9)
[VE-2204]: https://contentstack.atlassian.net/browse/VE-2204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Overlay calculation fix for hover leakage

src/liveEditor/components/fieldLabelWrapper.tsx, src/liveEditor/generators/generateHoverOutline.tsx, src/liveEditor/generators/generateOverlay.tsx, src/liveEditor/index.ts, src/liveEditor/listeners/mouseClick.ts, src/liveEditor/listeners/mouseHover.ts, src/liveEditor/utils/handleIndividualFields.ts, src/styles.css
1. When field is disabled, use a gray hover outline
2. When field is disabled and focussed, the focussed outline is also gray
=> feat: disabled state for hover outline and field focus outline

README.md, package.json, src/__test__/live-preview.test.ts, src/live-preview.ts, src/utils/defaults.ts, src/utils/handleUserConfig.ts
fix: removed code for default branch
=> fix: removed code for default branch

src/liveEditor/listeners/mouseClick.ts
Ref: [VE-2172](https://contentstack.atlassian.net/browse/VE-2172?atlOrigin=eyJpIjoiZjk1M2ZmZTc2ZTQ3NDhhNTkwODBhZWQ3MDI2NjA0NGQiLCJwIjoiaiJ9)
[VE-2172]: https://contentstack.atlassian.net/browse/VE-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: Field toolbar append issue

src/styles.css
Ref: [VE-2199](https://contentstack.atlassian.net/browse/VE-2199)
[VE-2199]: https://contentstack.atlassian.net/browse/VE-2199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Editable components cursor visibility style changes

src/liveEditor/components/fieldLabelWrapper.tsx
https://contentstack.atlassian.net/browse/VE-2352
=> Hide the caret if there are no parent paths

src/liveEditor/components/FieldToolbar.tsx, src/liveEditor/components/icons/index.tsx
https://contentstack.atlassian.net/browse/VE-2353
=> Disable navigation arrows based on position

src/liveEditor/utils/handleIndividualFields.ts, src/liveEditor/utils/normalizeNonBreakingSpace.ts
Ref: [VE-2202](https://contentstack.atlassian.net/browse/VE-2202)
[VE-2202]: https://contentstack.atlassian.net/browse/VE-2202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Multiline Text field enhancements

src/liveEditor/utils/multipleElementAddButton.ts
- Use a `MutationObserver` and observe parent and its sub-tree for mutations.
- When a mutation occurs, try to find the added instance/block using `data-cslp` and click on the found element to focus.
- If the element is not found after first mutation, disconnect the observer after timeout (4s).
=> feat: focus on added instance or block

src/liveEditor/generators/generateOverlay.tsx, src/styles.css
Reverts contentstack/live-preview-sdk#178
=> Revert "Overlay style and calculation changes"

src/styles.css
Reverts contentstack/live-preview-sdk#173
=> Revert "Editable components cursor visibility style changes"

src/liveEditor/index.ts
https://contentstack.atlassian.net/browse/VE-2376
=> VE-2376 Handle changes in element positions due to sidebar toggling or window resizing

src/liveEditor/generators/generateHoverOutline.tsx, src/liveEditor/listeners/index.ts, src/liveEditor/listeners/mouseClick.ts, src/liveEditor/utils/handleIndividualFields.ts
Capture click event during capture phase
=> fix: link navigation

src/liveEditor/generators/generateToolbar.tsx, src/liveEditor/utils/constants.ts
https://contentstack.atlassian.net/browse/VE-2349
=> Adjust toolbar position to prevent overlap when space is limited

src/liveEditor/generators/generateHoverOutline.tsx, src/liveEditor/listeners/mouseHover.ts, src/liveEditor/utils/getCsDataOfElement.ts
Ref: [VE-2489](https://contentstack.atlassian.net/browse/VE-2489)
[VE-2489]: https://contentstack.atlassian.net/browse/VE-2489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  Fix: Hover on editable element

src/liveEditor/generators/generateToolbar.tsx
https://contentstack.atlassian.net/browse/VE-2662
=> Consistent Toolbar Position

src/liveEditor/generators/generateToolbar.tsx, src/liveEditor/utils/constants.ts, src/styles.css
https://contentstack.atlassian.net/browse/VE-2354
=> VE-2354 Fix: Overflow & Cutoff on Right Edge

src/styles.css
Ref: [VE-2350](https://contentstack.atlassian.net/browse/VE-2350)
[VE-2350]: https://contentstack.atlassian.net/browse/VE-2350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Toolbar Dropdown buttons hover styles and contenteditable border remove

src/liveEditor/components/icons/fields/index.ts, src/liveEditor/listeners/mouseClick.ts, src/liveEditor/utils/constants.ts
Ref: [VE-2816](https://contentstack.atlassian.net/browse/VE-2816)
[VE-2816]: https://contentstack.atlassian.net/browse/VE-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Canvas URL field editing and mouse event blocking

src/liveEditor/generators/generateToolbar.tsx
Ref: [VE-2870](https://contentstack.atlassian.net/browse/VE-2870)
[VE-2870]: https://contentstack.atlassian.net/browse/VE-2870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Multiple Reference Instances' toolbar buttons

package-lock.json, package.json, src/__test__/live-preview.test.ts, src/live-preview.ts, src/utils/cslpdata.ts
fix: live preview: added variant support in data cslp tag function
=> fix: live preview: added variant support in data cslp tag function

package-lock.json, package.json, src/liveEditor/components/CommentIcon.tsx, src/liveEditor/components/FieldToolbar.tsx, src/liveEditor/components/addInstanceButton.tsx, src/liveEditor/components/emptyBlock.tsx, src/liveEditor/components/fieldLabelWrapper.tsx, src/liveEditor/components/icons/fields/custom.tsx, src/liveEditor/components/icons/fields/html-rte.tsx, src/liveEditor/components/icons/fields/isodate.tsx, src/liveEditor/components/icons/fields/json-rte.tsx, src/liveEditor/components/icons/fields/markdown-rte.tsx, src/liveEditor/components/icons/index.tsx, src/liveEditor/components/icons/loading.tsx, src/liveEditor/components/icons/url.tsx, src/liveEditor/components/icons/variant.tsx, src/liveEditor/components/index.tsx, src/liveEditor/components/pseudoEditableField.tsx, src/liveEditor/components/replaceAssetButton.tsx, src/liveEditor/components/startEditingButton.tsx, src/liveEditor/components/visualEditor.tsx, src/liveEditor/eventManager/useScrollToField.ts, tsup.config.js
Ref: [VE-3183](https://contentstack.atlassian.net/browse/VE-3183)
[VE-3183]: https://contentstack.atlassian.net/browse/VE-3183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Changes to support tsup/esbuild + preact

src/index.ts
feat: added export of IStackSDK type for Typscript contentstack SDK
=> feat: added export of IStackSDK type for Typscript contentstack SDK

src/visualBuilder/visualBuilder.style.ts
Ref: [VE-3036](https://contentstack.atlassian.net/browse/VE-3036)
[VE-3036]: https://contentstack.atlassian.net/browse/VE-3036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Custom mouse pointer z-index fix

src/configManager/handleUserConfig.ts
Ref: [VE-3259](https://contentstack.atlassian.net/browse/VE-3259)
[VE-3259]: https://contentstack.atlassian.net/browse/VE-3259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  Typescript Delivery SDK support

src/cms/types/contentTypeSchema.types.ts, src/visualBuilder/components/__test__/addInstanceButton.test.tsx, src/visualBuilder/components/addInstanceButton.tsx, src/visualBuilder/generators/generateAddInstanceButtons.tsx, src/visualBuilder/utils/handleIndividualFields.ts, src/visualBuilder/utils/multipleElementAddButton.ts, src/visualBuilder/visualBuilder.style.ts
- Use field value and schema to disable add instance button when maximum instances have been added
- Display a browser tooltip with a message indicating the same.
=> fix: disable add instance button when max. instances have been added

src/livePreview/eventManager/postMessageEvent.hooks.ts
Ref: [VE-3048](https://contentstack.atlassian.net/browse/VE-3048)
[VE-3048]: https://contentstack.atlassian.net/browse/VE-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added `mode` in init event post message

src/visualBuilder/generators/generateCustomCursor.ts, src/visualBuilder/generators/generateOverlay.tsx, src/visualBuilder/visualBuilder.style.ts
https://contentstack.atlassian.net/browse/VE-3573
=> VE-3573: Fix Custom Cursor Issues (Flicker & Additional Space) | IFrame Body Height Mismatch due to residual overlay

src/livePreview/eventManager/livePreviewEventManager.constant.ts, src/visualBuilder/eventManager/useRecalculateVariantDataCSLPValues.ts, src/visualBuilder/index.ts
https://contentstack.atlassian.net/browse/VE-3257
https://contentstack.atlassian.net/browse/VE-3481
requires : https://github.com/contentstack/visual-builder/pull/759
=> After Patch Update Variant Classes | Recalculate Variant Data CSLP Values

src/visualBuilder/components/CommentIcon.tsx, src/visualBuilder/components/FieldToolbar.tsx, src/visualBuilder/visualBuilder.style.ts
https://contentstack.atlassian.net/browse/VE-3823
=> Ve 3823 Tooltip Position Invert when space isn't available

src/visualBuilder/utils/handleIndividualFields.ts
https://contentstack.atlassian.net/browse/VE-4009
=> Psuedo-editable is created for multiple text field wrapper element

src/cslp/cslpdata.ts, src/visualBuilder/utils/getFieldType.ts, src/visualBuilder/utils/handleIndividualFields.ts
Ref: [VE-4048](https://contentstack.atlassian.net/browse/VE-4048)
[VE-4048]: https://contentstack.atlassian.net/browse/VE-4048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated logic for inline editing encompassing CT changes

src/visualBuilder/__test__/visualBuilderInput.test.tsx, src/visualBuilder/components/Collab/CollabIndicator.tsx, src/visualBuilder/components/Collab/ThreadPopup/CommentActionBar.tsx, src/visualBuilder/components/Collab/ThreadPopup/__test__/index.test.tsx, src/visualBuilder/components/Collab/ThreadPopup/index.tsx, src/visualBuilder/types/collab.types.ts, src/visualBuilder/utils/types/postMessage.types.ts
This change will add the ability to delete a thread when the last comment is deleted
=> Ve 4984 delete thread delete comment

src/visualBuilder/generators/generateThread.tsx, src/visualBuilder/index.ts, src/visualBuilder/types/collab.types.ts
REF :- [VE-5210](https://contentstack.atlassian.net/browse/VE-5210)
[VE-5210]: https://contentstack.atlassian.net/browse/VE-5210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> retry mechanism for thread rendering

src/visualBuilder/utils/__test__/getChildrenDirection.test.ts, src/visualBuilder/utils/getChildrenDirection.ts
https://contentstack.atlassian.net/browse/VE-5170
=> feat(VE-5170): add plus button configuration 

src/visualBuilder/components/HighlightedCommentIcon.tsx, src/visualBuilder/components/icons/index.tsx, src/visualBuilder/generators/generateHighlightedComment.tsx, src/visualBuilder/generators/generateThread.tsx, src/visualBuilder/hooks/useCollabIndicator.ts, src/visualBuilder/listeners/mouseClick.ts, src/visualBuilder/types/collab.types.ts
Ref :- [VE-5085](https://contentstack.atlassian.net/browse/VE-5085) , [VE-5322](https://contentstack.atlassian.net/browse/VE-5322)
[VE-5085]: https://contentstack.atlassian.net/browse/VE-5085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VE-5322]: https://contentstack.atlassian.net/browse/VE-5322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(collab): highlight comment icon fix and code optimization

src/visualBuilder/components/__test__/startEditingButton.test.tsx, src/visualBuilder/components/startEditingButton.tsx
https://contentstack.atlassian.net/browse/VE-5370
=> fix(VE-5370): start edit url updates on navigation

src/configManager/config.default.ts, src/types/types.ts, src/visualBuilder/collab.style.ts, src/visualBuilder/components/Collab/ThreadPopup/CommentTextArea.tsx, src/visualBuilder/components/Collab/Tooltip/Tooltip.tsx, src/visualBuilder/components/Collab/Tooltip/__test__/Tooltip.test.tsx, src/visualBuilder/eventManager/useCollab.ts, src/visualBuilder/eventManager/useHideFocusOverlayPostMessageEvent.ts, src/visualBuilder/generators/generateThread.tsx, src/visualBuilder/hooks/useCollabOperations.ts, src/visualBuilder/listeners/mouseHover.ts, src/visualBuilder/types/collab.types.ts, src/visualBuilder/utils/__test__/collabUtils.test.ts, src/visualBuilder/utils/collabUtils.ts, src/visualBuilder/utils/handleIndividualFields.ts
Ref:- [VE-5321](https://contentstack.atlassian.net/browse/VE-5321) , [VE-5416](https://contentstack.atlassian.net/browse/VE-5416) , [VE-5426](https://contentstack.atlassian.net/browse/VE-5426) , [VE-5427](https://contentstack.atlassian.net/browse/VE-5427) , [VE-5320](https://contentstack.atlassian.net/browse/VE-5320) , [VE-5430](https://contentstack.atlassian.net/browse/VE-5430)
[VE-5321]: https://contentstack.atlassian.net/browse/VE-5321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VE-5416]: https://contentstack.atlassian.net/browse/VE-5416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VE-5426]: https://contentstack.atlassian.net/browse/VE-5426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> fix(collab): bug fixes and code optimisations

src/index.ts, tsup.config.js
[VE-5392](https://contentstack.atlassian.net/browse/VE-5392)
[VE-5392]: https://contentstack.atlassian.net/browse/VE-5392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enable Tree shaking Feature

src/visualBuilder/listeners/mouseClick.ts, src/visualBuilder/listeners/mouseHover.ts, src/visualBuilder/utils/collabUtils.ts
Ref:- [VE-5463](https://contentstack.atlassian.net/browse/VE-5463)
[VE-5463]: https://contentstack.atlassian.net/browse/VE-5463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(collab): stop event propagation of modals in collab mode

src/visualBuilder/eventManager/useCollab.ts, src/visualBuilder/generators/generateThread.tsx, src/visualBuilder/utils/types/postMessage.types.ts
Ref:- [VE-5498](https://contentstack.atlassian.net/browse/VE-5498) , [VE-5517](https://contentstack.atlassian.net/browse/VE-5517)
[VE-5498]: https://contentstack.atlassian.net/browse/VE-5498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VE-5517]: https://contentstack.atlassian.net/browse/VE-5517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Handle edgecase of not rendering the indicator when the feature is disabled or paused

src/visualBuilder/components/Collab/CollabIndicator.tsx, src/visualBuilder/eventManager/useCollab.ts, src/visualBuilder/types/collab.types.ts, src/visualBuilder/utils/types/postMessage.types.ts
Ref:- [VE-5572](https://contentstack.atlassian.net/browse/VE-5572) , [VE-5568](https://contentstack.atlassian.net/browse/VE-5568)
[VE-5572]: https://contentstack.atlassian.net/browse/VE-5572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VE-5568]: https://contentstack.atlassian.net/browse/VE-5568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(collab): made the inviteMetada to be updated when refreshed to get new collaborators

src/__test__/data/fields.ts, src/visualBuilder/components/FieldToolbar.tsx, src/visualBuilder/components/__test__/fieldToolbar.test.tsx
https://contentstack.atlassian.net/browse/VE-5643
=> fix(VE-5643): Replace button is visible for parent wrapper for Multiple file field 

src/visualBuilder/generators/generateOverlay.tsx, src/visualBuilder/index.ts, src/visualBuilder/utils/__test__/focusOverlayWrapper.test.ts, src/visualBuilder/utils/__test__/handleFieldMouseDown.test.ts, src/visualBuilder/utils/handleFieldMouseDown.ts
Reverts contentstack/live-preview-sdk#411
=> Revert "fix: update field event is not sent when input event does not occur in inline editable fields"

src/index.ts, src/logger/logger.ts, src/visualBuilder/utils/collabUtils.ts
Ref :- [VE-6102](https://contentstack.atlassian.net/browse/VE-6102)
[VE-6102]: https://contentstack.atlassian.net/browse/VE-6102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(collab): add optional chaining for tree shaking

src/livePreview/__test__/live-preview.test.ts, src/livePreview/live-preview.ts
Please check: https://contentstack.atlassian.net/wiki/spaces/VC/pages/3453943812/Live+Preview+SDK+init+optimisation
=> Optimisation: `init` to emit postMessage on `DOMContentLoaded`
