.husky/pre-push
package-lock.json
package.json
src/__test__/contentstack-live-preview-HOC.test.ts

The package.json points to an incorrect file for the types; hence, the newer SDK version does not resolve the types.
Additionally, we have fixed a test case and added pre-push hooks to run test prior to every push
fixes: https://contentstack.atlassian.net/browse/CS-30634

fix: resolve types for typescript projects

---

src/liveEditor/index.ts
src/liveEditor/utils/__test__/generateStartEditingButton.test.ts
src/liveEditor/utils/__test__/multipleElementAddButton.test.ts
src/liveEditor/utils/multipleElementAddButton.ts

This PR will add a function to add plus buttons in multiple type fields like group and modular blocks. Additionally, it will move a test file to its correct folder.
Here is the list of tests performed
- generateAddButton
- should generate a button
- getChildrenDirection
- should return "none" if it is not a list type
- should return "none" if the parent container is not found
- should return 'vertical' if the parent container is found and the children are in a vertical list
- should return 'horizontal' if the parent container is found and the children are in a horizontal list
- should create a clone and determine direction when one child is present
- should return 'none' if the input is not provided
- should return "none" if the container does not contain the elements
- …

feat: handle add buttons during multiple

---

src/__test__/contentstack-live-preview-HOC.test.ts
src/live-preview.ts
src/liveEditor/__test__/__snapshots__/index.test.ts.snap
src/liveEditor/__test__/index.test.ts
src/liveEditor/index.ts
src/liveEditor/utils/generateStartEditingButton.ts
src/types/types.ts
src/utils/__test__/handleUserConfig.test.ts
src/utils/defaults.ts
src/utils/handleUserConfig.ts

The locale is required to determine which page should the visual editor open. This information is passed via the search params.
fixes: https://contentstack.atlassian.net/browse/VC-241

feat: add locale support for visual editor

---

src/liveEditor/__test__/index.test.ts
src/liveEditor/index.ts

The page is used to redirect to `/#!/live-editor`. But, it must redirect to `/live-editor`.
fixes: https://contentstack.atlassian.net/browse/EB-397

fix: redirect page to /live-editor

---

src/liveEditor/__test__/__snapshots__/index.test.ts.snap
src/liveEditor/__test__/index.test.ts
src/liveEditor/index.ts
src/liveEditor/utils/__test__/generateStartEditingButton.test.ts
src/liveEditor/utils/generateStartEditingButton.ts
src/styles.css

Converting the Start editing button will allow it to open the URL in the new tab.
fixes: https://contentstack.atlassian.net/browse/EB-398

feat: convert button to anchor tag

---

package-lock.json
src/liveEditor/__test__/__snapshots__/index.test.ts.snap
src/liveEditor/__test__/index.test.ts
src/liveEditor/__test__/withoutIframe.test.ts
src/liveEditor/index.ts

The start editing button should be shown only when we are outside the editor. It must be hidden when we are inside the editor.
fixes: https://contentstack.atlassian.net/browse/EB-404

feat: hide start editing button inside editor

---

src/liveEditor/index.ts
src/liveEditor/utils/__test__/focusOverlayWrapper.test.ts
src/liveEditor/utils/__test__/generateVisualEditorDom.test.ts
src/liveEditor/utils/focusOverlayWrapper.ts
src/liveEditor/utils/generateVisualEditorDom.ts

I have separated the logic for click and hide overlay. Now, the same logic is used for escape key and overlay click. Also, fixed some test cases to click the appropiate overlay.
fixes: https://contentstack.atlassian.net/browse/EB-562

feat: escape key closes the overlay

---

src/liveEditor/utils/focusOverlayWrapper.ts

We were adding inner HTML that adds the inline div elements. We replaced it with innerText if available as it retains the `\n`. However, if it is not available we fallback to text content.
fixes: https://contentstack.atlassian.net/browse/EB-817

fix: update field adds `<div/>` element

---

package-lock.json
package.json
src/__test__/contentstack-live-preview-HOC.test.ts
src/__test__/live-preview.test.ts
src/contentstack-live-preview-HOC.ts
src/live-preview.ts
src/utils/__test__/confighandler.test.ts
src/utils/configHandler.ts

The live preview editor will get the hash, content_type_uid, and entry_uid from the URL. So, we save them to the config and update the Stack SDK.
This will help us get the preview data from the first call and not wait for init.
fixes: https://contentstack.atlassian.net/browse/EB-890

feat: set live preview details from the URL

---

src/livePreview/editButton/__test__/editButton.test.ts
src/livePreview/editButton/__test__/shouldRenderEditButton.test.ts
src/livePreview/editButton/__test__/toggleEditButton.test.ts
src/livePreview/editButton/editButton.ts
src/livePreview/editButton/editButtonAction.test.ts
src/livePreview/live-preview.ts

Work has been completed on this Jira story : https://contentstack.atlassian.net/browse/EB-1201
This PR fixes a bug where the edit button appeared in the live editor. It introduces and takes the help of `Preact Effects` for better state updation
- Add `effect()` and update rendering logic in `editButton.ts`
- Update relevant test cases

EB-1201: Edit button is showing in live editor window

---

src/liveEditor/generators/__test__/generateToolbar.test.ts
src/liveEditor/generators/generateToolbar.tsx
src/liveEditor/utils/__test__/focusOverlayWrapper.test.ts
src/liveEditor/utils/handleIndividualFields.ts
src/livePreview/__test__/live-preview.test.ts

Work has been completed on this Jira story : https://contentstack.atlassian.net/browse/EB-1565
This PR focuses on fixing the sidebar load issue on the `live-preview-sdk` side 
- Placed `LiveEditorPostMessageEvents.OPEN_QUICK_FORM` appropriately  in `handleIndividualFields.ts`
- Fixed few minor bugs in test cases in `focusOverlayWrapper.test.ts` and `live-preview.test.ts`

EB-1565: Sidebar sometimes load and sometimes doesn't

---

src/cslp/__test__/cslpdata.test.ts
src/cslp/cslpdata.ts
src/cslp/types/cslp.types.ts
src/liveEditor/__test__/visualEditorClick.test.ts
src/liveEditor/__test__/visualEditorHover.test.ts
src/liveEditor/__test__/visualEditorInput.test.ts
src/liveEditor/components/__tests__/fieldLabelWrapper.test.tsx
src/liveEditor/components/__tests__/multipleFieldToolbar.test.tsx
src/liveEditor/generators/__test__/generateToolbar.test.ts
src/liveEditor/utils/__test__/focusOverlayWrapper.test.ts
src/liveEditor/utils/__test__/getCsDataOfElement.test.ts
src/liveEditor/utils/__test__/getExpectedFieldData.test.ts
src/liveEditor/utils/__test__/instanceHandler.test.ts
src/liveEditor/utils/__test__/multipleElementAddButton.test.ts

SDK's post-message payload now contains an added field, viz.:
```
...
instance: {
fieldPathWithIndex: <exact-field-path-of-the-field-focused>
}
...
```
We now use this path to focus on fields, particularly important in the case of multiple fields where focussing on a specific field inside an instance earlier did not navigate to that field in schema-form.

Introduced Instance's `fieldPathWithIndex` in post-message payloads

---

src/liveEditor/components/fieldLabelWrapper.tsx
src/liveEditor/utils/getFieldPathWithUid.ts
src/liveEditor/utils/types/postMessage.types.ts

Ticket: https://contentstack.atlassian.net/browse/VE-2048
To retrieve the fieldUid, to be able to display the correct name, entry was needed. For that, a new postmessage event is introduced that retrieves the fieldUid in the path of parent blocks, from visual editor.

Fix the bug that caused wrong fieldWrapper parent tags above blocks of a modularblock field

---

package-lock.json
package.json

1. UI-React branch https://github.com/contentstack/UI-React/tree/EB-1087-implement-live-preview-2-changes adds adv-post-message for LP related messaging
2. Bumping the SDK version passes the version compatibility check required for the internal usage of adv-post-message in UI-React.

chore: bump version for version compatibility with UI-React LP 2.0

---

src/liveEditor/components/pseudoEditableField.tsx
src/liveEditor/generators/generateOverlay.tsx
src/liveEditor/index.ts
src/liveEditor/listeners/mouseClick.ts
src/liveEditor/utils/handleFieldMouseDown.ts
src/liveEditor/utils/handleIndividualFields.ts
src/liveEditor/utils/normalizeNonBreakingSpace.ts

Fixes [VE-2182](https://contentstack.atlassian.net/browse/VE-2182)
1. Non-breaking space inserted on editing in content editable leads to unnecessary psuedo editable elements being inserted. Nbsp is now normalized to a standard whitespace.
2. Psuedo editable element was not being observed so new lines did not trigger an overlay update. The observer now observes and unobserves the psuedo editable correctly.
3. Enter is now disallowed for single line field type to match the standard text input
[VE-2182]: https://contentstack.atlassian.net/browse/VE-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: single line line break and unnecessary psuedo editable due to nbsp

---

src/liveEditor/components/FieldToolbar.tsx
src/liveEditor/components/__tests__/fieldLabelWrapper.test.tsx
src/liveEditor/components/fieldLabelWrapper.tsx
src/liveEditor/generators/generateHoverOutline.tsx
src/liveEditor/generators/generateToolbar.tsx
src/liveEditor/index.ts
src/liveEditor/listeners/index.ts
src/liveEditor/listeners/mouseClick.ts
src/liveEditor/listeners/mouseHover.ts
src/liveEditor/utils/constants.ts
src/liveEditor/utils/handleIndividualFields.ts
src/liveEditor/utils/updateFocussedState.ts
src/styles.css

Fixes: [VE-2250](https://contentstack.atlassian.net/browse/VE-2250)
- Update focussed state - toolbar (fieldpath dropdown and edit/replace buttons), overlays, overlay outline, psuedo editable on element resize.
- Some other improvements like setting up event listeners in fieldpath toolbar Preact component instead of adding a generic listener on parent wrapper; removing hover outline on mouseout, unobserving elements on cleanup.
[VE-2250]: https://contentstack.atlassian.net/browse/VE-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update focussed state and misc. improvements

---

src/liveEditor/listeners/mouseClick.ts
src/liveEditor/utils/getExpectedFieldData.ts
src/liveEditor/utils/getFieldData.ts
src/liveEditor/utils/handleIndividualFields.ts
src/liveEditor/utils/multipleElementAddButton.ts
src/liveEditor/utils/normalizeNonBreakingSpace.ts

Fixes [VE-2308](https://contentstack.atlassian.net/browse/VE-2308)
- Multiple instances are added at wrong index when the whole multiple field is selected instead of a particular index.
- We already fetch the field value, but we always fetched an instance value, the `getExpectedData --> getFieldData` now supports any path and can also return an object.
- Then, we can use `fieldValue.length` to specify the end index when the whole multiple field is selected.
[VE-2308]: https://contentstack.atlassian.net/browse/VE-2308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: multiple instance added at incorrect index

---

src/liveEditor/components/pseudoEditableField.tsx
src/liveEditor/generators/generateOverlay.tsx
src/liveEditor/utils/getMultilinePlaintext.ts
src/liveEditor/utils/handleIndividualFields.ts

Ref: [VE-2556](https://contentstack.atlassian.net/browse/VE-2556)
Only change required on the CSR side is this CSS (on the multiline element): 
```css
white-space: pre-line
```
`dangerouslySetHTML` not required
[VE-2556]: https://contentstack.atlassian.net/browse/VE-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- **Old state:** Bolds, italics or html allowed on multiline components and even get saved to CMS.
- **New state:** Bolds, italics or html show up just while editing contenteditable, **and change to plaintext as soon as user unfocusses**, only plaintext with newlines gets saved to CMS.
> Will have to take a separate ticket to block showing html styles while editing `contenteditable`.

 Multiline Field Support

---

src/liveEditor/components/visualEditor.tsx
src/liveEditor/index.ts
src/liveEditor/liveEditor.style.ts

Resolves [VE-3144](https://contentstack.atlassian.net/browse/VE-3144)
1. Hide contenteditable outline
2. Increase cursor z-index to 9999 (Academy team is using 1020 on their sidebar). We may need a better solution for this soon.
[VE-3144]: https://contentstack.atlassian.net/browse/VE-3144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide contenteditable outline

---

src/visualBuilder/components/FieldRevert/FieldRevertComponent.tsx
src/visualBuilder/components/fieldLabelWrapper.tsx

https://contentstack.atlassian.net/browse/VE-3355

VE-3355 send additional data for field revert

---

src/visualBuilder/utils/handleIndividualFields.ts

[contentstack.atlassian.net/browse/VE-4009](https://contentstack.atlassian.net/browse/VE-4009)

fix: pseudo editable element for multiple text fields

---

src/cslp/cslpdata.ts
src/visualBuilder/utils/handleIndividualFields.ts

Ref: [VE-4048](https://contentstack.atlassian.net/browse/VE-4048)
[VE-4048]: https://contentstack.atlassian.net/browse/VE-4048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated logic for inline editing considering CT changes

---

src/visualBuilder/utils/multipleElementAddButton.ts

https://contentstack.atlassian.net/browse/VE-4326

VE-4326: increase timeout for new instance to render

---

src/configManager/config.default.ts
src/configManager/handleUserConfig.ts
src/types/types.ts
src/visualBuilder/__test__/index.test.ts
src/visualBuilder/components/__test__/startEditingButton.test.tsx
src/visualBuilder/components/startEditingButton.tsx
src/visualBuilder/visualBuilder.style.ts

add ability to enable and disable the button
add ability to change the position of the button

feat(VE-4043): add start editing button configuration for builder mode

---

src/visualBuilder/listeners/mouseClick.ts

This is required to enable clicking on the "Edit in Studio" button displayed in the VB canvas which effectively opens the composable studio popup

feat: allow click on elements with studio-ui attribute

---

src/visualBuilder/generators/generateOverlay.tsx
src/visualBuilder/index.ts
src/visualBuilder/listeners/mouseClick.ts

Title: Added focus element observer to observe the focused element's data-cslp attribute and re-evaluate [handleBuilderInteraction](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) every time it changes.
Summary: This PR introduces a [MutationObserver](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) to monitor changes to the data-cslp attribute of the focused element. When the data-cslp attribute changes, the [handleBuilderInteraction](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) function is re-evaluated to …

fix(VE-5061): add observer to observe cslp of selected element

---

src/configManager/config.default.ts
src/types/types.ts
src/visualBuilder/components/Collab/ThreadPopup/CommentTextArea.tsx
src/visualBuilder/eventManager/useCollab.ts
src/visualBuilder/generators/generateThread.tsx
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/listeners/mouseHover.ts

Ref :- [VE-5243](https://contentstack.atlassian.net/browse/VE-5243)
[VE-5243]: https://contentstack.atlassian.net/browse/VE-5243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(collab): pause collab mode in preview share

---

src/livePreview/editButton/__test__/editButton.test.ts
src/livePreview/editButton/editButton.ts
src/visualBuilder/listeners/mouseClick.ts

Use a safezone based on the edit button positioning to decide whether the edit tag should be moved to a differnt element or not.

feat: improve edit button rendering

---

src/preview/contentstack-live-preview-HOC.ts

- Visual Builder doesn't send client-data-send on site load, this leads to
the site not making any calls to the preview service which is required
for the subsequent entry PATCH requests to work correctly.
- `onChangeCallback` is called when either `skipInitialRender` is false or
when live_preview search parameter is present in the URL. 
- Since Visual Builder provides these values through the search parameter, the site makes entry GET calls to the preview service. Since live preview doesn't provide these params in non-SSR modes, it will continue to work the same.

fix: call onChangeCallback when live_preview parameter is present in URL

---

src/visualBuilder/listeners/mouseClick.ts

when user clicks on an interactive element of the app in iframe with while holding the modifier key (in our case it is alt for windows, linux and option for macos) the clicks behaviour is not altered, which means interactive elements will be interactive while holding modifier key and clicking the element

VE-5544: Investigate button click issue with `data-cslp` attribute

---

src/visualBuilder/components/FieldToolbar.tsx
src/visualBuilder/visualBuilder.style.ts

This pull request includes several changes to the `FieldToolbarComponent` in `src/visualBuilder/components/FieldToolbar.tsx` to improve the user experience by adding a loading state and simplifying the focus handling logic. Additionally, it includes a minor style update in `visualBuilder.style.ts`.
* [`src/visualBuilder/components/FieldToolbar.tsx`](diffhunk://#diff-f6c42a815d3fabd6edadc896c760b89af1436ea73a81e7caeea252b1f107e32cR42): Added an import for `LoadingIcon` to use in the loading state.
* [`src/visualBuilder/components/FieldToolbar.tsx`](diffhunk://#diff-f6c42a815d3fabd6edadc896c760b89af1436ea73a81e7caeea252b1f107e32cL96-R112): Simplified the `handleFormFieldFocus` function by removing unnecessary parameters and returning the promise directly.
* …

fix: enhance loading state for form field focus

---

src/visualBuilder/generators/generateOverlay.tsx
src/visualBuilder/index.ts
src/visualBuilder/utils/__test__/focusOverlayWrapper.test.ts
src/visualBuilder/utils/__test__/handleFieldMouseDown.test.ts
src/visualBuilder/utils/handleFieldMouseDown.ts

A global state is used to track whether an input event was handled in the focused field.

fix: update field event is not sent when input event does not occur in inline editable fields

---

src/visualBuilder/utils/__test__/handleFieldMouseDown.test.ts
src/visualBuilder/utils/handleFieldMouseDown.ts

Since we prevent default (input) behaviour while we handle the space keydown, we must send the sync event which is sent while handling the input event

fix(VE-5803): sync field after custom space handling

---

src/visualBuilder/__test__/index.test.ts
src/visualBuilder/index.ts
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/utils/updateFocussedState.ts

Set unique ID on element click instead of mutation observer. This ensures that unique ID is only applied when multiple elements with the same CSLP are found.

fix: set unique ID on element click

---

CHANGELOG.md
src/visualBuilder/__test__/index.test.ts
src/visualBuilder/index.ts
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/utils/__test__/handleFieldMouseDown.test.ts
src/visualBuilder/utils/handleFieldMouseDown.ts
src/visualBuilder/utils/updateFocussedState.ts

This pull request introduces several updates and improvements to the `visualBuilder` module, focusing on handling duplicate elements, improving event handling, and enhancing test coverage. The changes include adding unique identifiers for duplicate elements, refining keydown handling for content-editable fields, and updating test cases to ensure robustness.
* Added logic in `src/visualBuilder/listeners/mouseClick.ts` to assign unique IDs (`data-cslp-unique-id`) to elements with duplicate `data-cslp` attributes, enabling more precise identification in functions like `updateFocussedState`.
* Updated `src/visualBuilder/utils/handleFieldMouseDown.ts` to handle `Space` key events in buttons more effectively, including syncing the field state using a throttled function. …

Stage-v3.2.1

---

src/visualBuilder/eventManager/__test__/useVariantsPostMessageEvent.spec.ts
src/visualBuilder/eventManager/useVariantsPostMessageEvent.ts
src/visualBuilder/utils/__test__/fieldSchemaMap.test.ts
src/visualBuilder/utils/fieldSchemaMap.ts

Clear field schema map on variant change as it contains a field - isUnlinkedVariant which depends on the current selected variant for its value.
The "get-variant-id" message is received from "Visual Builder" whenever the variant is changed.

fix(VE-6191): clear field schema map on variant change

---

src/visualBuilder/components/FieldRevert/FieldRevertComponent.tsx
src/visualBuilder/components/FieldToolbar.tsx
src/visualBuilder/components/__test__/fieldLabelWrapper.test.tsx
src/visualBuilder/components/__test__/fieldToolbar.test.tsx
src/visualBuilder/components/__test__/variantRevertDropdown.test.tsx
src/visualBuilder/components/fieldLabelWrapper.tsx
src/visualBuilder/generators/__test__/appendFieldToolbar.test.ts
src/visualBuilder/generators/__test__/generateToolbar.test.tsx
src/visualBuilder/generators/generateToolbar.tsx
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/listeners/mouseHover.ts
src/visualBuilder/utils/__test__/handleIndividualFields.test.ts
src/visualBuilder/utils/__test__/isFieldDisabled.test.ts
src/visualBuilder/utils/__test__/updateFocussedState.test.ts
src/visualBuilder/utils/__tests__/createCachedFetch.test.ts
src/visualBuilder/utils/createCachedFetch.ts
src/visualBuilder/utils/getEntryPermissions.ts
src/visualBuilder/utils/getEntryPermissionsCached.ts
src/visualBuilder/utils/handleIndividualFields.ts
src/visualBuilder/utils/isFieldDisabled.ts
src/visualBuilder/utils/updateFocussedState.ts
src/visualBuilder/visualBuilder.style.ts
vitest.setup.ts

Use get-permissions to request entry permissions from parent and disable certain actions such as inline editing, instance actions.

feat(VE-5851): disable fields of update restricted entries

---

src/visualBuilder/__test__/hover/fields/boolean.test.ts
src/visualBuilder/__test__/hover/fields/date.test.ts
src/visualBuilder/__test__/hover/fields/file.test.ts
src/visualBuilder/__test__/hover/fields/group.test.ts
src/visualBuilder/__test__/hover/fields/html-rte.test.ts
src/visualBuilder/__test__/hover/fields/json-rte.test.ts
src/visualBuilder/__test__/hover/fields/link.test.ts
src/visualBuilder/__test__/hover/fields/markdown.test.ts
src/visualBuilder/__test__/hover/fields/multi-line.test.ts
src/visualBuilder/__test__/hover/fields/number.test.ts
src/visualBuilder/__test__/hover/fields/reference.test.ts
src/visualBuilder/__test__/hover/fields/select.test.ts
src/visualBuilder/__test__/hover/fields/single-line.test.ts
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/listeners/mouseHover.ts

- Add error handling for getPermissionsCached usage

fix(VE-5851): error handling for getEntryPermissionsCached

---

src/visualBuilder/generators/generateStartEditingButton.tsx
src/visualBuilder/index.ts
src/visualBuilder/utils/__test__/generateStartEditingButton.test.ts

The start editing button was not getting rendered as it was loaded inside the visual-builder_container which was only visible inside the visual builder

fix: start editing button not rendering

---

src/visualBuilder/utils/__test__/getPsuedoEditableEssentialStyles.test.ts
src/visualBuilder/utils/__test__/getPsuedoEditableStylesElement.test.ts
src/visualBuilder/utils/getPsuedoEditableEssentialStyles.ts
src/visualBuilder/utils/getPsuedoEditableStylesElement.ts

The height of the cloned/psuedo-editable element collapses when text-wrap-mode is set to nowrap and text-overflow is set to ellipsis. This change ensures that we override these properties CORRECTLY. Previously we overrode these properties but only in camel case. Now we ensure we perform the camelCase transformation after overriding properties. We also set min-height to whatever the current height of the element is, to prevent height collapse in other scenarios.

fix(VE-6459): psuedo-editable height collapse

---

.talismanrc
package-lock.json
package.json
src/__test__/utils.ts
src/visualBuilder/components/Tooltip.tsx
src/visualBuilder/components/__test__/fieldLabelWrapper.test.tsx
src/visualBuilder/components/fieldLabelWrapper.tsx
src/visualBuilder/components/icons/index.tsx
src/visualBuilder/eventManager/useReferenceMapEvent.ts
src/visualBuilder/generators/generateToolbar.tsx
src/visualBuilder/index.ts
src/visualBuilder/listeners/index.ts
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/listeners/mouseHover.ts
src/visualBuilder/utils/__test__/enableInlineEditing.test.ts
src/visualBuilder/utils/handleIndividualFields.ts
src/visualBuilder/utils/types/postMessage.types.ts
src/visualBuilder/visualBuilder.style.ts

Ref: [VE-6701](https://contentstack.atlassian.net/browse/VE-6701)
https://github.com/user-attachments/assets/81cb7af4-6c36-4475-a766-d28c939f68e9
[VE-6701]: https://contentstack.atlassian.net/browse/VE-6701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat: HoverToolbar] Component and rendering logic changes

---

src/visualBuilder/generators/generateOverlay.tsx
src/visualBuilder/index.ts
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/listeners/mouseHover.ts

Found this issue while manual testing, when a container content is focussed -> hovering on any child content was changing the toolbar content => Fixed this

Fix: HoverToolbar to not render when focussed

---

src/visualBuilder/components/FieldToolbar.tsx

This Pr modifies the way we were fetching field location data

Ve 6955 field location data fails to render when toolbar isnt mounted and event listener is missing

---

src/visualBuilder/listeners/mouseHover.ts

https://github.com/user-attachments/assets/99fea840-f46b-47e2-b746-02db64ff8e55
https://github.com/user-attachments/assets/07297805-8314-466a-908d-90b68b7ec4e2

Fix: Issue with hover toolbar click-ability

---

src/livePreview/eventManager/livePreviewEventManager.constant.ts
src/livePreview/eventManager/livePreviewEventManager.ts
src/livePreview/eventManager/postMessageEvent.hooks.ts
src/livePreview/eventManager/types/livePreviewPostMessageEvent.type.ts

This pull request introduces a new `ON_RELOAD` event to the live preview system, enabling enhanced functionality for handling reload scenarios. The changes span multiple files, adding support for the new event and ensuring proper integration into the live preview event manager and hooks.
- **Constant definition**: Added `ON_RELOAD` to the `LIVE_PREVIEW_POST_MESSAGE_EVENTS` object in `src/livePreview/eventManager/livePreviewEventManager.constant.ts`.
- **Event handling**: Updated the `EventManager` initialization in `src/livePreview/eventManager/livePreviewEventManager.ts` to dynamically set the `target` based on the presence of `window.opener`.
- **New hook**: Created `useOnReloadPostMessageEvent` in `src/livePreview/eventManager/postMessageEvent.hooks.ts` to listen for the `ON_RELOAD` …

feat: live preview: added outside iframe code

---

src/visualBuilder/components/__test__/emptyBlock.test.tsx
src/visualBuilder/components/emptyBlock.tsx
src/visualBuilder/visualBuilder.style.ts

The Font Awesome icon (`fas fa-plus`) was not rendering correctly because:
- **No Font Awesome dependency** in the project's `package.json`
- **Relied on external dependency** - the icon was likely working due to Font Awesome being included as a starter dependency in consuming applications
- **Inconsistent rendering** across different environments where Font Awesome wasn't available

VE-6918 : warning message improved 

---

src/livePreview/__test__/live-preview.test.ts
src/livePreview/eventManager/postMessageEvent.hooks.ts
src/utils/__test__/addLivePreviewQueryTags.test.ts
src/utils/__test__/index.test.ts
src/utils/addLivePreviewQueryTags.ts
src/utils/index.ts

fix: multiple reloads in timeline
Ticket -> https://contentstack.atlassian.net/browse/VE-6673
Test Report -> 
This pull request introduces enhancements to the live preview functionality, focusing on improving query parameter handling, adding support for timeline-specific behavior, and refining event listener logic. The most important changes include updates to query parameter management, adjustments to event handling, and integration of timeline-specific checks.
* [`src/utils/addLivePreviewQueryTags.ts`](diffhunk://#diff-5faee81be2d4fdc18aed05c48429bfb9ef08f4869bf041ad8f6693b6c62eebcbL11-R21): Added support for the `preview_timestamp` query parameter and refined logic for adding `live_preview`, `content_type_uid`, and `entry_uid` query parameters.
* …

fix: multiple reloads in timeline

---

src/visualBuilder/__test__/click/fields/multi-line.test.tsx
src/visualBuilder/__test__/click/fields/number.test.tsx
src/visualBuilder/__test__/click/fields/single-line.test.tsx
src/visualBuilder/components/FieldToolbar.tsx
src/visualBuilder/components/__test__/fieldLabelWrapper.test.tsx
src/visualBuilder/components/fieldLabelWrapper.tsx
src/visualBuilder/generators/__test__/generateToolbar.test.ts
src/visualBuilder/generators/__test__/generateToolbar.test.tsx
src/visualBuilder/generators/generateToolbar.tsx
src/visualBuilder/listeners/mouseClick.ts
src/visualBuilder/listeners/mouseHover.ts
src/visualBuilder/utils/__test__/handleIndividualFields.test.ts
src/visualBuilder/utils/__test__/isFieldDisabled.test.ts
src/visualBuilder/utils/__test__/updateFocussedState.test.ts
src/visualBuilder/utils/fetchEntryPermissionsAndStageDetails.ts
src/visualBuilder/utils/getEntryPermissions.ts
src/visualBuilder/utils/getWorkflowStageDetails.ts
src/visualBuilder/utils/handleIndividualFields.ts
src/visualBuilder/utils/isFieldDisabled.ts
src/visualBuilder/utils/types/postMessage.types.ts
src/visualBuilder/utils/updateFocussedState.ts

Fetch workflow stage details for the entry from parent and disable editing based on the received data.

feat(VB-132 | VE-7062): disable editing when workflow stage rules restrict the same 
